import subprocess
import os
import sys
import time
from pathlib import Path

def get_latest_benchmark_dir(base_out_dir):
    """Find the latest timestamp directory in benchmark_out"""
    p = Path(base_out_dir)
    if not p.exists():
        return None
    # Filter for directories that look like timestamps (YYYYMMDD_HHMMSS)
    subdirs = [d for d in p.iterdir() if d.is_dir() and d.name[0].isdigit()]
    if not subdirs:
        return None
    # Sort by name (which is timestamp) descending
    return sorted(subdirs, key=lambda x: x.name, reverse=True)[0]

def run_script(script_path, description, args=None, env=None):
    print(f"\n{'='*60}")
    print(f"STEP: {description}")
    print(f"Script: {script_path}")
    print(f"{'='*60}\n")
    
    if not os.path.exists(script_path):
        print(f"Error: Script not found: {script_path}")
        return False

    try:
        # Run the script and capture output
        # Using sys.executable to ensure the same python interpreter is used
        result = subprocess.run([sys.executable, script_path], check=True)
        if result.returncode == 0:
            print(f"\n[SUCCESS] {description} completed.")
            return True
        else:
            print(f"\n[FAILURE] {description} failed with code {result.returncode}.")
            return False
    except subprocess.CalledProcessError as e:
        print(f"\n[FAILURE] {description} failed: {e}")
        return False
    except Exception as e:
        print(f"\n[ERROR] An error occurred: {e}")
        return False

def main():
    pipeline_start = time.time()
    base_dir = Path(__file__).resolve().parent
    
    # Define steps
    steps = [
        {
            "script": "stt_to_json.py",
            "desc": "1. STT (Speech to Text) - Audio to JSON"
        },
        {
            "script": "poc_flash_test.py",
            "desc": "2. Intent Classification (Filter Invalid Queries)"
        },
        {
            "script": "simple_keyword_extractor_gemini.py",
            "desc": "3. Keyword Extraction - Extract Intent from Utterance"
        },
        {
            "script": "expand_keywords_comparison_gemini.py",
            "desc": "4. Keyword Expansion - Generate Search Keywords & TSV for Benchmark"
        },
        # # Step 4.25: Export DB to TSV - SKIPPED (already indexed)
        # {
        #     "script": "export_db_to_tsv.py",
        #     "desc": "4.25 Export DB - Convert local SQLite to TSV for Indexing"
        # },
        # # Step 4.5: Indexing (Qdrant/Elastic) - SKIPPED (already indexed)
        # {
        #     "script": "index_external_hybrid.py",
        #     "desc": "4.5 Indexing - Push data to Qdrant/Elastic"
        # },
        # Step 5: Run Benchmark (LYG) - Needs arguments
        {
            "script": "run_benchmark.py",
            "desc": "5. Retrieval Benchmark (Vector/BM25)",
            "args": [
                "--vendors", "poc/data/benchmark_out/20260205_071633/configs/vendors.yaml",
                "--pipelines", "poc/data/benchmark_out/20260205_071633/configs/pipelines.yaml",
                "--vendor-set", "ext_qdrant_elastic", # Use external Qdrant/Elastic
                "--pipeline", "hybrid_fuse", # Use Hybrid pipeline
                "--pipeline", "hybrid_fuse", # Use Hybrid pipeline
                "--catalog", "poc/lyg/data/catalog.sqlite_export.tsv", # Use exported SQLite catalog (Integer IDs)
                "--testcases", "backend/services_kms/data/expansion_result.tsv", # Generated by Step 3
                "--out", "backend/services_kms/data/benchmark_out"
            ],
            "capture_output": True # Need to capture output to get run dir if needed, mainly for log
        }
    ]
    
    # Step 6: Rerank (KDG) - will be constructed dynamically in the loop because it needs dynamic args
    steps.append({
        "script": "poc_v5_experiment_phase_1.py",
        "desc": "6. Advanced Reranking (Gemini Flash) - Apply KDG Logic",
        "dynamic": True # Flag to indicate args need dynamic generation
    })

    print("Starting Daiso Category Search Pipeline...")
    
    env = os.environ.copy()
    env["CATALOG_TSV"] = "poc/lyg/data/catalog.sqlite_export.tsv"
    
    step_times = []  # Collect timing for each step
    
    for step in steps:
        script_full_path = str(base_dir / step["script"])
        args = step.get("args", [])
        
        # --- Value Injection for Dynamic Steps ---
        if step.get("dynamic") and "poc_v5_experiment_phase_1.py" in step["script"]:
             # Use project root for benchmark output (2 levels up from backend/services_kms)
             project_root = base_dir.parent.parent
             benchmark_out_root = project_root / "backend/services_kms/data/benchmark_out"
             latest_run_dir = get_latest_benchmark_dir(benchmark_out_root)
             if not latest_run_dir:
                 print(f"\n[SKIP] {step['desc']} - No benchmark output found.")
                 continue
             
             # args: --run-dir <latest> --catalog <env_var> --out <fixed_path>
             args = [
                 "--run-dir", str(latest_run_dir),
                 "--catalog", str(project_root / "poc/lyg/data/catalog.sqlite_export.tsv"),
                 "--out", str(project_root / "backend/services_kms/data/final_reranked_results.json")
             ]

        # Special check for Step 4 config existence
        if "run_benchmark.py" in step["script"]:
             if not os.path.exists(str(base_dir / args[1])): # vendors
                 print(f"Warning: Vendors config not found at {args[1]}. Using template if exists or skipping.")
             # For robustness, we try to run it. If it fails, we assume user needs to config.

        cmd = [sys.executable, script_full_path] + args
        
        print(f"\n{'='*60}")
        print(f"STEP: {step['desc']}")
        print(f"Command: {' '.join(cmd)}")
        print(f"{'='*60}\n")
        
        step_start = time.time()
        try:
            subprocess.run(cmd, check=True, env=env)
            step_elapsed = time.time() - step_start
            step_times.append((step['desc'], step_elapsed))
            print(f"\n[SUCCESS] {step['desc']} completed. ({step_elapsed:.2f}s)")
        except subprocess.CalledProcessError as e:
            step_elapsed = time.time() - step_start
            step_times.append((step['desc'], step_elapsed))
            print(f"\n[FAILURE] {step['desc']} failed: {e} ({step_elapsed:.2f}s)")

    print(f"\n{'='*60}")
    print("PIPELINE COMPLETED SUCCESSFULLY!")
    print(f"{'='*60}")
    print("Output Files:")
    print(f"1. STT Output:       backend/services_kms/data/stt_output.json")
    print(f"2. Intent Analysis:  backend/services_kms/data/intent_output.json")
    print(f"3. Extracted Keys:   backend/services_kms/data/extracted_keywords.json")
    print(f"4. Expanded Keys:    backend/services_kms/data/expansion_result.tsv")
    
    benchmark_out_root = base_dir / "data/benchmark_out"
    final_run_dir = get_latest_benchmark_dir(benchmark_out_root)
    final_run_name = final_run_dir.name if final_run_dir else "UNKNOWN"
    
    print(f"5. Retrieval Result: backend/services_kms/data/benchmark_out/{final_run_name}/detail.jsonl")
    print(f"6. Final Selection:  backend/services_kms/data/final_reranked_results.json")
    
    # Step timing breakdown
    print(f"\n{'='*60}")
    print("Step Timing:")
    for desc, elapsed in step_times:
        print(f"  - {desc}: {elapsed:.2f}s")
    
    total_time = time.time() - pipeline_start
    print(f"\n[Total Time] {total_time:.2f} seconds ({total_time/60:.1f} minutes)")

if __name__ == "__main__":
    main()
